name: build_and_deploy
on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: pwsh

jobs:
  build:
    uses: ./.github/workflows/build_package.yaml
    with:
      solutionFile: ./brandon.parks.Test.NuGet/brandon.parks.Test.NuGet.sln
      nugetDirecory: ./brandon.parks.Test.NuGet/bin/Release
    
  deploy:
    name: Deploy Package
    needs: [build]
    runs-on: windows-2022
    environment: Production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: nuget

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
    
      - name: Publish NuGet Package
        run: |
          dotnet nuget push *.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
