name: deploy
on:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: pwsh

jobs:
  deploy:
    name: Deploy Package
    runs-on: windows-2022
    environment: Production

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: nuget
          github-token: ${{ secrets.GH_PAT }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
    
      - name: Publish NuGet Package
        run: |
          dotnet nuget push *.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
