name: publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

defaults:
  run:
    shell: pwsh

env:
  SolutionFile: ./brandon.parks.Test.NuGet/brandon.parks.Test.NuGet.sln
  ProjectFile: brandon.parks.Test.NuGet/brandon.parks.Test.NuGet/brandon.parks.Test.NuGet.csproj
  NuGetDirectory: ./brandon.parks.Test.NuGet/bin/Release

jobs:
  check_version:
    name: Check Version Number
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          path: current
          sparse-checkout: ${{ env.ProjectFile }}

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: main
          sparse-checkout: ${{ env.ProjectFile }}

      - name: Find version number
        shell: bash
        run: |
          ls
          ls main
          ls current
          version_current=$(grep '<Version>' ./current/${{ env.ProjectFile }} | grep -Eo "[0-9]+/.[0-9]+/.[0-9]+-?/w*")
          version_main=$(grep '<Version>' ./main/${{ env.ProjectFile }} | grep -Eo "[0-9]+/.[0-9]+/.[0-9]+-?/w*")
          echo $version_current
          echo $version_main

  build:
    name: Build Package
    needs: check_version
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore NuGet Packages
        run: nuget restore ${{ env.SolutionFile }}

      - name: Build Project
        run: msbuild ${{ env.SolutionFile }} /p:Configuration=Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nuget
          if-no-files-found: error
          path: ${{ env.NuGetDirectory }}/*nupkg

  deploy:
    name: Deploy Package
    needs: [check_version, build]
    runs-on: windows-2022

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: nuget

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
    
      - name: Publish NuGet Package
        run: |
          dotnet nuget push *.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
