name: test_build
on:
  pull_request:
    branches:
      - 'main'

jobs:
  check_version:
    uses: ./.github/workflows/check_version.yaml
    with:
      projectFile: brandon.parks.Test.NuGet/brandon.parks.Test.NuGet/brandon.parks.Test.NuGet.csproj
  
  build:
    uses: ./.github/workflows/build_package.yaml
    needs: check_version
    with:
      solutionFile: ./brandon.parks.Test.NuGet/brandon.parks.Test.NuGet.sln
      nugetDirecory: ./brandon.parks.Test.NuGet/bin/Release
